import 'package:google_maps_flutter/google_maps_flutter.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Station {

  Station({
    required this.id,
    required this.code,
    required this.mobileNum,
    required this.area,
    required this.province,
    required this.city,
    required this.name,
    required this.businessName,
    required this.address,
    required this.lat,
    required this.lng,
    required this.type,
    required this.depotId,
    required this.dealerId,
    required this.createdAt,
    required this.updatedAt,
  });

  late final int id;
  late final String code;
  late final String mobileNum;
  late final String area;
  late final String province;
  late final String city;
  late final String name;
  late final String businessName;
  late final String address;
  late final String lat;
  late final String lng;
  late final String type;
  late final int depotId;
  late final int dealerId;
  late final String? createdAt;
  late final String? updatedAt;

  LatLng get getPosition => LatLng(double.parse(lat), double.parse(lng));

  Station.fromJson(Map<String, dynamic> json){
    id = json['id'];
    code = json['code'];
    mobileNum = json['mobileNum'];
    area = json['area'];
    province = json['province'];
    city = json['city'];
    name = json['name'];
    businessName = json['businessName'];
    address = json['address'];
    lat = json['lat'];
    lng = json['lng'];
    type = json['type'];
    depotId = json['depotId'];
    dealerId = json['dealerId'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
  }

  Map<String, dynamic> toJson() {
    final _data = <String, dynamic>{};
    _data['id'] = id;
    _data['code'] = code;
    _data['mobileNum'] = mobileNum;
    _data['area'] = area;
    _data['province'] = province;
    _data['city'] = city;
    _data['name'] = name;
    _data['businessName'] = businessName;
    _data['address'] = address;
    _data['lat'] = lat;
    _data['lng'] = lng;
    _data['type'] = type;
    _data['depotId'] = depotId;
    _data['dealerId'] = dealerId;
    _data['createdAt'] = createdAt;
    _data['updatedAt'] = updatedAt;
    return _data;
  }
}
